import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import { Bootstrap } from "@/bootstrap";
import 'mdb-react-ui-kit/dist/css/mdb.min.css';
import "@fortawesome/fontawesome-free/css/all.min.css";
import "./globals.css";

import { SideProfile } from "@/app/side-profile";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <div className="custom-container pb-3">
            <div className="container">
              <div className="row">
                <SideProfile />
                { children }
              </div>
            </div>
          </div>
          <Bootstrap />
      </body>
    </html>
  );
}
